import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'
import { OutLineMenu } from '@/components/layout/OutLineMenu'

export const NotoSansKR = Noto_Sans_KR({
  display: 'swap',
  preload: true,
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSansKR.className} antialiased`}>
        <OutLineMenu>{children}</OutLineMenu>
      </body>
    </html>
  )
}
