import type { Metadata } from 'next'
import { Noto_Sans_KR, Poppins } from 'next/font/google'

import './globals.css'
import { OutLineMenu } from '@/components/layout/OutLineMenu'

export const NotoSansKR = Noto_Sans_KR({
  display: 'swap',
  preload: true,
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const PoppinsFont = Poppins({
  display: 'swap',
  preload: true,
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${PoppinsFont.className} ${NotoSansKR.className} antialiased`}
      >
        <OutLineMenu>
          <div className="w-content-limit mx-auto max-w-full py-40 mobile:pl-2">
            {children}
          </div>
        </OutLineMenu>
      </body>
    </html>
  )
}
