name: 'Testing'

on:
  push:
    branches: [main]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: pnpm install
        uses: ./pnpm.yml
      - name: Jest Testing
        run: pnpm run test --watchAll=false

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: pnpm install
        uses: ./pnpm.yml
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
